### ISSUE TITLE
1.18.2无法加载，plib为最新构建版

### ISSUE THREAD

**Issue by Coquettishpig** [Rothes/ProtocolStringReplacer#38]
[19:35:37 ERROR]: Could not load 'plugins\ProtocolStringReplacer v2.17.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at java.nio.file.Files.copy(Files.java:3128) ~[?:?]
        at me.rothes.protocolstringreplacer.ProtocolStringReplacer.saveExampleReplacers(ProtocolStringReplacer.java:341) ~[ProtocolStringReplacer v2.17.3.jar:?]
        at me.rothes.protocolstringreplacer.ProtocolStringReplacer.checkConfig(ProtocolStringReplacer.java:315) ~[ProtocolStringReplacer v2.17.3.jar:?]
        at me.rothes.protocolstringreplacer.ProtocolStringReplacer.<init>(ProtocolStringReplacer.java:105) ~[ProtocolStringReplacer v2.17.3.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more

**Comment by Rothes** [comment]
无法复现，purpur-1.18.2-1632.jar，由于有IO操作，可能是系统差异导致的问题

**Comment by Rothes** [comment]
请提供系统版本, 尝试最新开发构建以帮助了解是哪一个示例配置文件造成的问题.
v2.17.1 未修改示例配置解压逻辑, 可以正常运作. 可在解压后更新至最新版本.

**Comment by Rothes** [comment]
dee27ee418e95e295f788d683f5f92b6be6cafb4 已解决，编码问题
