### ISSUE TITLE
后台报错

### ISSUE THREAD

**Issue by nnn950711** [Rothes/ProtocolStringReplacer#6]
**Describe the bug**
[19:14:13 ERROR]: [ProtocolStringReplacer] Unhandled exception occured in onPacketSending(PacketEvent) for ProtocolStringReplacer
java.lang.RuntimeException: Unable to clone object PacketContainer[type=ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[private final int net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.a, private final java.util.List net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.b]]] (com.comphenix.protocol.events.PacketContainer)
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:256) ~[?:?]
        at me.rothes.protocolstringreplacer.packetlisteners.server.EntityMetadata$1.onPacketSending(EntityMetadata.java:29) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:421) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2044) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2030) ~[?:?]
        at net.minecraft.server.level.ServerEntity.a(ServerEntity.java:302) ~[?:?]
        at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:285) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2443) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2354) ~[?:?]
        at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2099) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2120) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1069) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:932) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:758) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1285]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1000, banned: 0], return=Exact class net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata, params=[{Type: Exact class net.minecraft.network.PacketDataSerializer, Index: 0}], paramCount=1}
        at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:330) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1224) ~[?:?]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378) ~[?:?]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2212) ~[?:?]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:495) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[?:?]
        ... 33 more
[19:14:13 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@476e1c3d[
    a=3508
    b=[net.minecraft.network.syncher.DataWatcher$Item@5c1a1439, net.minecraft.network.syncher.DataWatcher$Item@c249834, net.minecraft.network.syncher.DataWatcher$Item@318bea19, net.minecraft.network.syncher.DataWatcher$Item@13df16b3, net.minecraft.network.syncher.DataWatcher$Item@1fe8632d, net.minecraft.network.syncher.DataWatcher$Item@3725bddc, net.minecraft.network.syncher.DataWatcher$Item@59904203, net.minecraft.network.syncher.DataWatcher$Item@3291ad0c, net.minecraft.network.syncher.DataWatcher$Item@6e3c5178, net.minecraft.network.syncher.DataWatcher$Item@74edca3e]
  ]

[19:14:13 ERROR]: [ProtocolStringReplacer] Unhandled exception occured in onPacketSending(PacketEvent) for ProtocolStringReplacer
java.lang.RuntimeException: Unable to clone object PacketContainer[type=ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=77], structureModifier=StructureModifier[fieldType=class java.lang.Object, data=[private final int net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.a, private final java.util.List net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata.b]]] (com.comphenix.protocol.events.PacketContainer)
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:256) ~[?:?]
        at me.rothes.protocolstringreplacer.packetlisteners.server.EntityMetadata$1.onPacketSending(EntityMetadata.java:29) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:421) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2044) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2030) ~[?:?]
        at net.minecraft.server.level.ServerEntity.a(ServerEntity.java:302) ~[?:?]
        at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:285) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2443) ~[?:?]
        at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2354) ~[?:?]
        at net.minecraft.server.level.ChunkMap.processTrackQueue(ChunkMap.java:2099) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:2120) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1069) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:932) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:758) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1629) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1285]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1285]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find a method that matches {modifiers=[required: 1000, banned: 0], return=Exact class net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata, params=[{Type: Exact class net.minecraft.network.PacketDataSerializer, Index: 0}], paramCount=1}
        at com.comphenix.protocol.reflect.FuzzyReflection.getMethod(FuzzyReflection.java:174) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.readObject(PacketContainer.java:330) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1224) ~[?:?]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378) ~[?:?]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2212) ~[?:?]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:495) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:453) ~[?:?]
        at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:42) ~[?:?]
        ... 33 more
[19:14:13 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutEntityMetadata@120340e1[
    a=3509
    b=[net.minecraft.network.syncher.DataWatcher$Item@62d51c15, net.minecraft.network.syncher.DataWatcher$Item@cd4f82e, net.minecraft.network.syncher.DataWatcher$Item@35b76cdc, net.minecraft.network.syncher.DataWatcher$Item@4f037e8b, net.minecraft.network.syncher.DataWatcher$Item@57ce6ca, net.minecraft.network.syncher.DataWatcher$Item@2e426bc3, net.minecraft.network.syncher.DataWatcher$Item@201d235b, net.minecraft.network.syncher.DataWatcher$Item@743ef6f5, net.minecraft.network.syncher.DataWatcher$Item@1616140e, net.minecraft.network.syncher.DataWatcher$Item@2bb7697c]
  ]

**Server Informations**
 - Minecraft Version: git-Purpur-1283 (MC: 1.17.1)
 - ProtocolLib Version: ProtocolLib-4.7.0
 - ProtocolStringReplacer Version: ProtocolStringReplacer v1.4.0

**Comment by Rothes** [comment]
猜测是由Holographic全息插件导致，且应在ProtocolLib中反馈

**Comment by Rothes** [comment]
新版本v1.4.1将屏蔽该类报错，但仍建议在ProtocolLib上反馈该问题.
